clone_depth: 10

# Needs this for most recent MSYS
image: Visual Studio 2019

environment:
  global:
    MSYS2_DIR: C:\msys64
    MSYS2_ASH: C:\msys64\usr\bin\ash.exe
    MSYS2_BASH: C:\msys64\usr\bin\bash.exe

cache:
  - '%MSYS2_DIR%\var\cache\pacman'

install:
  - '%MSYS2_BASH% --login -c "pacman -Syu --noconfirm"'
  - '%MSYS2_BASH% --login -c "pacman -S --noconfirm --needed git openssl rsync p7zip"'
  - '%MSYS2_BASH% --login -c "pacman -S --noconfirm --needed p7zip"'

  - '%MSYS2_BASH% --login -c "cd $APPVEYOR_BUILD_FOLDER && curl -fsSLOJ https://github.com/egraff/winsible/releases/download/v0.1.1/winsible.7z"'
  - '%MSYS2_BASH% --login -c "curl -fsSLOJ https://github.com/chrislake/7zsfxmm/releases/download/1.7.0.3900/7zsd_extra_170_3900.7z"'
  - '%MSYS2_BASH% --login -c "TARGET_DIR=`cd $APPVEYOR_BUILD_FOLDER && pwd` && mkdir $TARGET_DIR/7zsd_extra && 7z e 7zsd_extra_170_3900.7z -o$TARGET_DIR/7zsd_extra"'

build_script:
  - '%MSYS2_BASH% --login -c "cd $APPVEYOR_BUILD_FOLDER && ./release.sh"'

artifacts:
  - path: winconfig-install.exe
    name: installer
    type: file
