---
- import_tasks: registry_general_tweaks.yml

- import_tasks: terminal_settings.yml

- import_tasks: windows_update_configuration.yml

- import_tasks: remove_appx_packages.yml

- import_tasks: windows_power_settings.yml

- import_tasks: windows_locale.yml

- import_tasks: install_choco_packages.yml

- import_tasks: install_notepadplusplus.yml

- import_tasks: install_git.yml

- import_tasks: install_vscode.yml

- import_tasks: install_msys.yml
