---
- name: 'Enable long paths'
  ansible.windows.win_regedit:
    state: present
    path: HKLM:\SYSTEM\ControlSet001\Control\FileSystem
    name: LongPathsEnabled
    data: 1
    type: dword

- name: 'Enable long paths'
  ansible.windows.win_regedit:
    state: present
    path: HKLM:\SYSTEM\CurrentControlSet\Control\FileSystem
    name: LongPathsEnabled
    data: 1
    type: dword

- name: '.NET: use the "System Default" TLS versions'
  ansible.windows.win_regedit:
    state: present
    path: HKLM:\SOFTWARE\Microsoft\.NETFramework\v4.0.30319
    name: SystemDefaultTlsVersions
    data: 1
    type: dword

- name: '.NET (32-bit): use the "System Default" TLS versions'
  ansible.windows.win_regedit:
    state: present
    path: HKLM:\SOFTWARE\WOW6432Node\Microsoft\.NETFramework\v4.0.30319
    name: SystemDefaultTlsVersions
    data: 1
    type: dword

- name: 'Disable Hide extensions for known file types'
  ansible.windows.win_regedit:
    state: present
    path: HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced
    name: HideFileExt
    data: 0
    type: dword

- name: 'Read UserPreferencesMask'
  ansible.windows.win_reg_stat:
    path: HKCU:\Control Panel\Desktop
    name: UserPreferencesMask
  register: user_preferences_mask

- name: 'Disable ClickLock'
  ansible.windows.win_regedit:
    state: present
    path: HKCU:\Control Panel\Desktop
    name: UserPreferencesMask
    data: '{{ user_preferences_mask.value[:1] + [ user_preferences_mask.value[1] | bitwise_and("0x7f" | int(base=16)) ] + user_preferences_mask.value[2:] }}'
    type: binary
