---
- name: 'Terminal: configure font size (current user)'
  ansible.windows.win_regedit:
    path: HKCU:\Console
    name: FontSize
    data: 0x00100000
    type: dword

- name: 'Terminal: configure font size (default user)'
  ansible.windows.win_regedit:
    path: HKU:\.DEFAULT\Console
    name: FontSize
    data: 0x00100000
    type: dword

- name: "Terminal: don't use legacy console (current user)"
  ansible.windows.win_regedit:
    path: HKCU:\Console
    name: ForceV2
    data: 1
    type: dword

- name: "Terminal: don't use legacy console (default user)"
  ansible.windows.win_regedit:
    path: HKU:\.DEFAULT\Console
    name: ForceV2
    data: 1
    type: dword

- name: 'Terminal: enable insert mode (current user)'
  ansible.windows.win_regedit:
    path: HKCU:\Console
    name: InsertMode
    data: 1
    type: dword

- name: 'Terminal: enable insert mode (default user)'
  ansible.windows.win_regedit:
    path: HKU:\.DEFAULT\Console
    name: InsertMode
    data: 1
    type: dword

- name: 'Terminal: enable line selection (current user)'
  ansible.windows.win_regedit:
    path: HKCU:\Console
    name: LineSelection
    data: 1
    type: dword

- name: 'Terminal: enable line selection (default user)'
  ansible.windows.win_regedit:
    path: HKU:\.DEFAULT\Console
    name: LineSelection
    data: 1
    type: dword

- name: 'Terminal: enable line wrap (current user)'
  ansible.windows.win_regedit:
    path: HKCU:\Console
    name: LineWrap
    data: 1
    type: dword

- name: 'Terminal: enable line wrap (default user)'
  ansible.windows.win_regedit:
    path: HKU:\.DEFAULT\Console
    name: LineWrap
    data: 1
    type: dword

- name: 'Terminal: enable quick edit (current user)'
  ansible.windows.win_regedit:
    path: HKCU:\Console
    name: QuickEdit
    data: 1
    type: dword

- name: 'Terminal: enable quick edit (default user)'
  ansible.windows.win_regedit:
    path: HKU:\.DEFAULT\Console
    name: QuickEdit
    data: 1
    type: dword

- name: 'Terminal: set screen buffer size (current user)'
  ansible.windows.win_regedit:
    path: HKCU:\Console
    name: ScreenBufferSize
    data: 655294584
    type: dword

- name: 'Terminal: set screen buffer size (default user)'
  ansible.windows.win_regedit:
    path: HKU:\.DEFAULT\Console
    name: ScreenBufferSize
    data: 655294584
    type: dword
