---
- name: 'Configure Automatic Updates: Enabled'
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate\AU
    name: NoAutoUpdate
    data: 0
    type: dword

- name: 'Configure Automatic Updates: Auto download and notify for install'
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate\AU
    name: AUOptions
    data: 3
    type: dword

- name: 'No auto-restart with logged on users for scheduled automatic updates installations: Enabled'
  ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate\AU
    name: NoAutoRebootWithLoggedOnUsers
    data: 1
    type: dword
