---
- hosts: all
  vars_prompt:
    - name: ansible_user
      prompt: What is your username?
      private: no
    - name: ansible_password
      prompt: What is your password?
  roles:
    - role: winconfig
